### ISSUE TITLE
ModuleNotFoundError: No module named 'encoder'

### ISSUE THREAD

**Issue by prey176** [snap-stanford/neural-subgraph-learning-GNN#1]
We were running the test file in the subgraph_matching folder (as given in the README) with the command "python3 -m subgraph_matching.test --node_anchored".
And received the error "ModuleNotFoundError: No module named 'encoder'" on the line 128. I believe the encoder file is not uploaded.

**Comment by prey176** [comment]
Error got resolved.
Change the line 128 "from encoder.train import main" to "from subgraph_matching.train import main". It will work.

**Comment by qema** [comment]
Thanks for the catch -- fixed in the repo.
