### ISSUE TITLE
question on subgraph alignment code

### ISSUE THREAD

**Issue by shopeth** [snap-stanford/neural-subgraph-learning-GNN#11]
Hello,

Thank you for sharing the code for the interesting work. I got a question on this part of the alignment code:

https://github.com/snap-stanford/neural-subgraph-learning-GNN/blob/219dd709db78977a0ee274fdee6b8db6cda0db65/subgraph_matching/alignment.py#L53

Is the query and target position switched? In the model forwarding, it seems the first position pos_a is the supergraph of second position pos_b. Current work will generate the opposite prediction.

**Comment by qema** [comment]
Hi yes thank you for the catch :) our internal code had this fixed, but I had forgotten to update the public repo. We are working on an improved version with more robust alignment code and support for node features. Updated the current repo to use the correct ordering of query and target
