### ISSUE TITLE
[Question] - About edge labels

### ISSUE THREAD

**Issue by LafLaurine** [snap-stanford/neural-subgraph-learning-GNN#21]
Hi! I have another question for you 😃

I am still working with your library and I was wondering if labels edges were used during frequent mining?

In the pattern_growth function in the decoder file, we can see that the task can be "graph-labeled". I saw in a previous issue that it is not possible to make use of node labels in the current repo but  does the method in this article use the edge label information?

Thanks in advance!

**Comment by qema** [comment]
Thanks for your interest! Unfortunately edge labels are not currently supported (the graph labels refer to using datasets of multiple graphs where each graph has a label). See the `experimental` branch (https://github.com/snap-stanford/neural-subgraph-learning-GNN/issues/16#issuecomment-860029505) for a way to use node labels.

**Comment by LafLaurine** [comment]
Thank you very much for your answer! Looking forward this experimental branch.
