### ISSUE TITLE
Generating negative query sample 

### ISSUE THREAD

**Issue by abhishekrajgaria** [snap-stanford/neural-subgraph-learning-GNN#5]
In common/data.py under the class DiskDataSource method gen_batch line 336:-

![image](https://user-images.githubusercontent.com/30906709/97305160-c2538280-1882-11eb-8325-62b2da53fd95.png)

The argument of filter_negs = False by default line 287 and neither it is set True at the time of calling, 
Setting this "False" by default may cause an issue like adding a positive query into the negative query-target dataset. As it is passing the query_graph without testing it.

**Comment by RexYing** [comment]
Yes there will be false negative if it is set to True. However, we estimated the amount of false negatives when the option is turned off. The proportion is generally <1%. For training the model can mostly be robust to these amount of false labels. 
The purpose is mostly to improve the speed of training data generation, and we can go through millions of iterations with generated data relatively easily with this option turned off.

**Comment by abhishekrajgaria** [comment]
Thanks, got it.
