### ISSUE TITLE
what should the pickle file of the query and target graphs be?

### ISSUE THREAD

**Issue by jams-xin** [snap-stanford/neural-subgraph-learning-GNN#7]
what should the pickle file of the query and target graphs be? Is there a reference example？ Thank you!

**Comment by qema** [comment]
The pickle file for both query and target should contain a single undirected networkx graph object. If either query or target is not provided, the script will default to a random example graph

**Comment by jams-xin** [comment]
Thank you for your reply. In the process of reproducing your code, after converting the original graph data into a netwokx graph object, I am not sure whether the category of the node label in the original graph data still exists. Does the method in this article use the node label information. If the node label is used, where is it used? If not, how to distinguish different label nodes in the graph.Thank you very much.

**Comment by qema** [comment]
Unfortunately it is not possible to make use of node labels in the current repo. The functionality is implemented and we are working on incorporating it into the repository with a proper interface. Thank you for your interest and patience!

**Comment by jams-xin** [comment]
You are so cool. But could you please provide the code for implementing the function of making use of node labels now? If possible, my email is yunxin366@gmail.com.Thank you very much!

**Comment by jams-xin** [comment]
You are so cool. But could you please provide the code for implementing the function of making use of node labels now? If possible, my email is yunxin366@gmail.com. Thank you very much!

**Comment by qema** [comment]
Sent you an email!

**Comment by jams-xin** [comment]
Thank you for your patience and answers.

**Comment by shopeth** [comment]
@qema hello I was wondering if you could send me the implementation to utilize node labels too? It'll be quite useful for a recent project. My email is sh.opeth@gmail.com. Thank you!

**Comment by qema** [comment]
Sent!

**Comment by wenchiangh** [comment]
@qema hello I was wondering if you could send me the implementation to utilize node labels too? It'll be quite useful for a recent project. My email is [wenchiangh@gmail.com](wenchiangh@gmail.com). Thank you! I have see changes of experimental branches, specially  `subgraph_mining/decoder.py` but I still can't find how the code use node labels and can't understand why all subgraph of nodes relabel from zero, in my mind after this action, information of nodes has been lost.

**Comment by wOvOpy** [comment]
@jams-xin @shopeth Could you give me the code with the node labels mentioned in the question above? Thank you very much. My email address is wOvOpy@gmail.com.

**Comment by wOvOpy** [comment]
@qema hello, I am wondering the code that utilize node labels too, could you send it to me. Thank you!
